.eslintignore
.eslintrc.js
.gitignore
.npmignore
.travis.yml
LICENSE
README.md
index.js
lib/config.js
lib/static/report.css
lib/static/report.js
lib/templates/report.hbs
lib/templates/state.hbs
lib/templates/suite.hbs
lib/view-model.js
lib/view.js
package.json
test/.eslintrc.js
test/index.js
test/lib/config.js
test/lib/view-model.js
test/lib/view.js
test/mocha.opts
test/setup.js
utils.js

/cc @j0tunn, @sipayRT, @eGavr, @tormozz48, @DudaGod

feat: implement core functionality

---

lib/templates/report.hbs

Moved from PR https://github.com/gemini-testing/gemini/pull/782 by @dustyo-O

Added charset to report template

---

lib/view-model.js
test/index.js
test/lib/view-model.js

//cc @rostik404 @sipayRT @eGavr @DudaGod @j0tunn

fix: fix error with double slashed suite urls

---

index.js
test/index.js

//cc @j0tunn @levonet @DudaGod @rostik404 @eGavr

Fix issue with empty report on image reference update

---

index.js
test/index.js

//cc @rostik404 @DudaGod @j0tunn @eGavr

fix: fix missed image file issue on gemini update

---

.gitignore
README.md
index.js
lib/config.js
lib/templates/report.hbs
lib/view-model.js
test/index.js
test/lib/view-model.js

added **option errorsOnly** - build report with only fail tests

Report improvments

---

.gitignore
.travis.yml
package-lock.json
package.json

// cc @rostik404 @DudaGod @eGavr

feat: drop support of node below 6.x

---

lib/static/components/state/index.js
lib/static/components/state/meta-info.js
lib/view-model.js
test/lib/view-model.js

```
"metaInfo": {
"url": "/yandexPage",
"file": "gemini/test.js",
"sessionId": "0b2958a78b5eafdb02087f635e54a4a4"
}
```

Change metaInfo in data.js from html-string to object

---

lib/report-builder-factory/report-builder.js
test/lib/report-builder-factory/report-builder.js

fix: empty title for hermione test

---

package.json

chore: add watcher for webpack

---

lib/static/gui.css
lib/static/styles.css

fix: mark with red tests failed with error

---

.eslintignore
.gitignore
.npmignore
webpack.common.js

Do not save a lot of `*.hot-update.json` and `*.hot-update.js` files

fix: webpack watcher

---

lib/common-utils.js
lib/gui/tool-runner-factory/gemini/report-subscriber.js
lib/report-builder-factory/report-builder.js
lib/static/components/gui.js
lib/static/components/state/index.js
lib/static/components/state/state-error.js
lib/static/gui.css
lib/static/modules/reducer.js
lib/static/modules/utils.js
lib/static/styles.css
test/lib/report-builder-factory/report-builder.js

chore(gui): handle skip events

---

lib/static/styles.css

fix: inline diff images in one row

---

lib/gui/app.js
lib/gui/tool-runner-factory/base-tool-runner.js
test/lib/gui/app.js
test/utils.js

Все перепроверил: кейсы с ошибками, с разными ретраями для браузеров, с --retry.
Решил так:
- RUN перезапускает все тесты с обычным ретраем
- RETRY FAILED TEST  – без ретраев
- RETRY – без ретраев

Fix retry button retries multiple times

---

lib/static/components/section/section-base.js
lib/static/components/section/section-browser.js
lib/static/components/section/section-common.js
lib/static/modules/utils.js

// cc @DudaGod @rostik404
Do not expand browser section for updated suite

fix(gui): collapse suite after image accept

---

lib/gui/app.js
lib/gui/server.js
lib/gui/tool-runner-factory/base-tool-runner.js
test/lib/gui/app.js
test/lib/gui/server.js
test/lib/gui/tool-runner-factory/base-tool-runner.js

После этого PRа - выпускаю версию.

chore: do not share reportBuilder from tool

---

lib/gui/tool-runner-factory/base-tool-runner.js
lib/plugin-adapter.js
lib/report-builder-factory/index.js
lib/report-builder-factory/report-builder.js
lib/test-adapter/gemini-test-adapter.js
lib/test-adapter/hermione-test-adapter.js
lib/test-adapter/test-adapter.js
test/hermione.js
test/lib/test-adapter/gemini-test-adapter.js
test/lib/test-adapter/hermione-test-adapter.js
test/utils.js

cc @sipayRT @DudaGod @rostik404

feat(hermione): show the first 'assertView' command result

---

lib/static/components/state/meta-info.js

fix: do not fail in gui actions

---

lib/static/styles.css

fix(scaleImages): diff images can be higher than actual and expected

---

lib/static/modules/actions.js

* did not work in the case when test errored in th last retry

fix: accept image from one of retries

---

lib/merge-reports/report-builder.js
test/lib/merge-reports/report-builder.js

* move files/dirs from 1st source report to destination report
* do not move data.js file

fix(merge-reports): move only existent content

---

lib/static/modules/actions.js

reproduced when running the test in multiple browsers

fix(gui): do not fail on accept image

---

lib/static/styles.css

fix: reset native paddings from retry-buttons

---

lib/merge-reports/data-tree.js

Есть гипотеза, что это быстрофикс для INFRADUTY-2409.
P.S. fs-extra здесь очень-очень старый, но обновлять его в рамках критикала нет времени.

fix: не падать, а перезаписывать файл

---

.gitignore
lib/static/components/section/section-common.js
lib/static/components/suites.js
lib/static/components/summary/index.js
lib/static/modules/reducer.js
lib/static/modules/utils.js
test/lib/static/modules/utils.js

Depends on https://github.com/gemini-testing/hermione/pull/370

feat: added ability to filter browser by url params

---

lib/merge-reports/data-tree.js
test/lib/merge-reports/data-tree.js

сс @DudaGod @rostik404 @DudaGod

fix: do not fail if one of the reports is empty

---

lib/constants/defaults.js
lib/static/components/state/diff-circle.js
lib/static/components/state/index.js
lib/static/components/state/screenshot.js
lib/static/components/state/state-fail.js
lib/static/styles.css
lib/test-adapter/gemini-test-adapter.js
lib/test-adapter/hermione-test-adapter.js
package-lock.json
package.json
test/lib/static/components/section/diff-circle.js
test/lib/test-adapter/gemini-test-adapter.js
test/lib/test-adapter/hermione-test-adapter.js

Маленький дифф
Большой дифф
Из-за пары конвертеров, через которые прошли эти гифки, кажется, что анимация лагает. На самом деле, все плавно. 
Смотреть только первый коммит - во втором статика для тестирования.
/cc @sipayRT @DudaGod

 feat: add circles to diff by click

---

lib/static/components/controls/common-controls.js
lib/static/components/controls/menu-bar.js
lib/static/components/state/placeholder.js
lib/static/styles.css

//cc @DudaGod @rostik404 @CatWithApple

fix(css): maximize menubar item click area

---

lib/static/components/state/index.js
lib/static/components/state/screenshot.js
lib/static/components/state/state-fail.js
lib/test-adapter/gemini-test-adapter.js
lib/test-adapter/hermione-test-adapter.js
test/lib/test-adapter/gemini-test-adapter.js
test/lib/test-adapter/hermione-test-adapter.js

feat: add diff clusters

---

lib/static/components/controls/common-controls.js
lib/static/components/suites.js
lib/static/modules/default-state.js
package-lock.json
package.json
test/lib/static/components/suites.js

if `lazyLoadOffset` is enabled so all `SectionCommon` components (suites) will be wrapped with `LazilyRender` component to prevent render for suites outside of the viewport. It will be common option for lazy-render and lazy-image-load functionality

feat: lazy suite render

---

lib/gui/api/index.js
lib/gui/constants/gui-events.js
lib/gui/server.js
test/lib/gui/api/index.js
test/lib/gui/server.js

Added event when server is ready. Going to use this to profile time from process start to gui opening.

feat: 'serverReady' event

---

lib/static/gui.css
lib/static/styles.css

Controls should be more visible and balanced between one another.
Before and after:

fix(a11y): make icons more visible

---

lib/static/modules/actions.js
lib/static/modules/local-storage-wrapper.js
lib/static/modules/reducer.js
test/unit/lib/static/modules/local-storage-wrapper.js
test/unit/lib/static/modules/reducer.js
test/unit/utils.js

Issue: https://github.com/gemini-testing/html-reporter/issues/243

feat: add ability to save filter state

---

lib/static/styles.css

fix: do not cover Accept button by images

---

lib/merge-reports/data-tree.js
test/unit/lib/merge-reports/data-tree.js

Исправлено падение при мердже отчетов с отсутствующими скриншотами.

fix: merging reports without screenshots

---

.hermione.conf.js
package-lock.json
package.json

Добавление тайтла к каждой секции теста на стабах репортера для удобного матчинга  в интеграционных тестах.

test: add title to each section on stub

---

lib/static/components/section/body/index.js
lib/static/components/section/switcher-retry.js
lib/static/styles.css
test/unit/lib/static/components/section/switcher-retry.js

Выбран success ретрай:
Выбран failed ретрай:

feat: show retry status

---

lib/server-utils.js
test/unit/lib/server-utils.js
test/unit/lib/test-adapter.js

in case when the same test was skipped at first run and was unskipped at second run

fix(gui): do not increase retry count for skipped tests

---

lib/static/gui.css

Reverts gemini-testing/html-reporter#291
it looks not ok

Revert "feat(gui): add min{-height, -width} to  .button_type_suite-controls class"

---

lib/static/components/state/screenshot.js
test/unit/lib/static/components/section/screenshot.js

fix(screenshot): wrong path for screenshots on Windows

---

lib/static/gui.css
lib/static/styles.css

- fix text position in browser list;
- decrease vertical indentation for retries
- add vertical indentation for error details

fix(style): fix indentation between elements

---

lib/static/components/section/section-common.js
lib/static/components/section/section-wrapper.js
lib/static/styles.css

- fix size of the section icons which is located near with root section title
- fix indentation for last details element

fix(style): fix bugs in the new design

---

package-lock.json
package.json

Up gemini-core version to 5.3.0 that uses png-img@3.0.0 with prebuilt binaries.

fix: up gemini-core version

---

lib/static/components/details.js
test/unit/lib/static/components/section/body/meta-info.js
test/unit/lib/static/components/state/state-error.js

Problem is described here - https://nda.ya.ru/t/LlnNIOpg3XdmUq

fix: bug with visibility inside "Details" component

---

lib/constants/errors.js
lib/static/components/retry-switcher/item.js
lib/static/modules/utils.js
lib/static/styles.css
test/unit/lib/static/components/retry-switcher/item.js

Screenshot - https://nda.ya.ru/t/ZIsnQB333XdcFu

feat: separate image errors from other asserts by color in retry switcher

---

lib/static/components/retry-switcher/item.js
test/unit/lib/static/components/retry-switcher/item.js

fix: bug with switch color for diff in retry switcher

---

package-lock.json
package.json

gemini-core@6.1.0 contains png-img@3.3.0 which supports NodeJS 14 and prebuild for it.

fix: up version of gemini-core to 6.1.0

---

lib/static/modules/reducers/tree.js
lib/static/modules/selectors/tree.js
lib/tests-tree-builder/base.js
test/unit/lib/static/modules/reducers/tree.js
test/unit/lib/static/modules/selectors/tree.js
test/unit/lib/tests-tree-builder/base.js

fix(html-reporter): update tree status on filter selection

---

package-lock.json
package.json

png-img@3.3.0 supports Node 14: https://github.com/gemini-testing/png-img/pull/55

fix: get png-img@3.3.0 from hermione@^3.11.0/gemini-core@^6.1.0

---

README.md
lib/config/index.js
lib/static/modules/load-plugin.js
lib/static/modules/plugins.js
test/unit/lib/static/modules/load-plugin.js
test/unit/lib/static/modules/plugins.js

I need to pass some configuration to my plugin.
This PR adds it

feat(plugins): add plugin configuration

---

lib/static/modules/actions.js

In my plugins I want to use notifications. This PR export notification actions.

feat(plugins): add export of createNotification actions

---

lib/static/modules/selectors/tree.js
lib/static/modules/utils.js
test/unit/lib/static/modules/selectors/tree.js

- incorrect counting of the number of images on click "Accept opened"
- incorrect counting of the number of errors in the "Group by error" mode
- incorrect counting of the number of tests to run by button "Retry failed tests"

fix(gui): errors

---

lib/plugin-api.js
lib/static/components/controls/base-host-input.js
lib/static/components/controls/browser-list.js
lib/static/components/controls/common-controls.js
lib/static/components/controls/common-filters.js
lib/static/components/controls/controls.less
lib/static/components/controls/gui-controls.css
lib/static/components/controls/gui-controls.js
lib/static/components/controls/report-controls.js
lib/static/components/controls/report-info.js
lib/static/components/controls/selects/index.styl
lib/static/components/header/header.css
lib/static/components/header/index.js
lib/static/components/header/summary/summary.css
lib/static/styles.css

- Добавлено поле `version` в объект htmlReporter, содержит значение из `package.json`
- В GUI и статическом отчете добавлен label с версией
- В статическом отчете изменено расположение даты для более гармоничного дизайна
Счекаутить ветку и собрать локально
- Запускал GUI на локальном тестовом проекте, собирал отчет на локальном тестовом проекте. Пробовал различную ширину окна
Обратите внимание на плитки "Version" и "Created at" рядом со стандартными контролами в меню

Add version to htmlReporter object and UI, report creation date redesign

---

lib/static/components/header/summary/dbBtn.js
lib/static/components/header/summary/dbSummary.js

Пофиксил баг, из-за которого попап на загруженных базах данных улетал влево вверх на позицию (0, 0)
Просто вынес эту кнопку в отдельный файл

fix: db popup inconsistent position

---

lib/static/components/modals/screenshot-accepter/index.js
lib/static/modules/utils.js
test/unit/lib/static/components/modals/screenshot-accepter/index.js

Реализовал предзагрузку следующих изображений в `screenshot-accepter`

perf: preload images in screenshot-accepter mode

---

lib/gui/tool-runner/index.ts
package-lock.json
package.json
test/unit/lib/gui/tool-runner/index.js

Add cli options "devtools" and "replMode" to hermione "readTests" and "run" methods

fix: correctly pass cli options to hermione "readTests" and "run"

---

lib/static/components/controls/controls.less
lib/static/components/controls/run-button/index.styl
lib/static/components/controls/selects/index.styl
lib/static/components/suites.jsx
lib/static/containers/array/array.styl
lib/static/gui.css
lib/static/styles.css
lib/static/variables.css

What has been done:
- border-radius values are unified (for buttons, inputs, selects, popups)
- colors of the hover are unified
- checkboxes are aligned relative to the text
Before:
After:

chore(css): polishing css styles

---

lib/adapters/tool/testplane/index.ts
package.json

- fix support hermione, it was broken in #551
- specify pwt in peer deps

fix: support hermione

---

lib/bundle/transformer.ts
package-lock.json
package.json

- move "@gemini-testing/commander" from devDeps to deps
- correctly import ts config with types for playwright

fix(pwt): correctly import ts config with types

---

lib/constants/test-statuses.ts
lib/static/new-ui.css
lib/static/new-ui/features/suites/components/SuitesPage/index.tsx
lib/static/new-ui/features/suites/components/SuitesTreeView/index.module.css
lib/static/new-ui/features/suites/components/SuitesTreeView/selectors.ts
lib/static/new-ui/features/suites/components/TestStatusFilter/index.module.css
lib/static/new-ui/features/suites/components/TestStatusFilter/index.tsx
lib/static/new-ui/features/suites/components/TestStatusFilter/selectors.ts
lib/static/new-ui/store/selectors.ts
lib/static/new-ui/types/store.ts
lib/static/new-ui/utils/index.tsx
lib/static/styles.css

Example report: https://nda.ya.ru/t/VLqVLf-d77fFpu
⚠️ This PR is based on #590, only the last commit needs review (`feat: implement filtering by status in new ui`).

feat: implement filtering by status in new ui

---

lib/constants/diff-modes.ts
lib/static/components/state/index.jsx
lib/static/new-ui/components/AssertViewResult/index.module.css
lib/static/new-ui/components/AssertViewResult/index.tsx
lib/static/new-ui/components/AttemptPicker/index.tsx
lib/static/new-ui/components/AttemptPickerItem/index.module.css
lib/static/new-ui/components/DiffViewer/index.module.css
lib/static/new-ui/components/DiffViewer/index.tsx
lib/static/new-ui/components/DiffViewer/utils.ts
lib/static/new-ui/features/suites/components/SuitesPage/index.module.css
lib/static/new-ui/features/suites/components/TestSteps/index.module.css
lib/static/new-ui/features/suites/components/TestSteps/index.tsx
lib/static/new-ui/features/suites/components/TestSteps/selectors.ts
lib/static/new-ui/features/suites/components/TestSteps/types.ts
lib/static/new-ui/features/suites/components/TestSteps/utils.ts
lib/static/new-ui/store/selectors.ts
lib/static/new-ui/types/store.ts
lib/static/new-ui/utils/index.tsx
lib/static/styles.css

⚠️ This PR is based on #600. **Only last commit needs review.**
Test reports:
- With various screenshot states: https://nda.ya.ru/t/G-eslI5L78GALr
- Large project: https://nda.ya.ru/t/gGn-IsIl78GAgR

chore(new-ui): implement screenshots display

---

lib/static/new-ui/components/DiffViewer/SideBySideToFitMode.module.css
lib/static/new-ui/components/DiffViewer/utils.ts
lib/static/new-ui/components/Screenshot/index.module.css

Original user's report, with fix from this PR: https://nda.ya.ru/t/mFurBb-x79eJMr
My custom report with tons of different image aspect ratios: https://nda.ya.ru/t/zPwpfy4F79eJUT

fix: fix diff bubbles in side-by-side fit screen mode

---

lib/static/modules/reducers/tree/helpers.js
lib/static/modules/reducers/tree/index.js
lib/static/modules/reducers/tree/nodes/browsers.js
lib/static/modules/utils/index.js

[Demo report](https://nda.ya.ru/t/Stn52JHO7FZnj4)

fix: use old search algorithm in old ui

---

lib/tests-tree-builder/base.ts
test/unit/lib/tests-tree-builder/base.js

We used to have 2 places with square asymptotics, and now they are linear as well

perf: speed up tests tree builder construction
