lib/static/components/state/screenshot.js
lib/static/styles.css

Hi!
I tried to use this reporper for screenshots with Retina-display, so I got really big screenshots (because they have size twice bigger that I set in the settings) and they weren't fit in a window:
https://pp.userapi.com/c841227/v841227183/5da4e/sN88XePETyI.jpg
It seems not so useful, so I fixed the styles to make screenshots fit:
https://pp.userapi.com/c841227/v841227183/5da44/zxNM5M13Xvc.jpg
What do you think about it?

Make big screenshots fit in a small window

---

lib/static/components/section/section-base.js
lib/static/components/section/section-browser.js
lib/static/components/section/section-common.js
lib/static/components/suites.js
lib/static/modules/reducer.js

Наверное, замечали, что если в html-reporter нажимать на следующие кнопки и вводить данные в поля:
заново раскрываются все сьюты, а на больших тестах отчет начинает тормозить. Так вот, это поведение было вызвано тем, что на каждое это действие заново рендерилось все дерево сьютов. Это поведение исправлено.
В ходе работы были найдены 2 проблемы:
1. Кнопка `ExpandRetries` работает некорректно.
В самом коде:
```js
if (expand === 'errors' && failed || updated) {
return false;
} else if (showRetries && retried) {
return false;
}
```
явно прописано, что она имеет меньшее значение, чем `Expand errors`. Это очень путает, не логично, и приводит к неправильному поведению. А самое главное, кнопка свою функцию не выполняет.
2. При клике на `ExpandAll`, `Collapse All` и `Expand Errors` дерево сьютов …

Render only affected parts of page

---

lib/static/components/suites.js

This is a temporary hack before the fix of the real problem in
chrome browser (unknown errors in a browser console) 
which causes closing of event source connection

fix(hack): do not close connection on event source error

---

lib/gui/tool-runner-factory/gemini/index.js

`metaInfo` looses `file` property in serialized `data.js` when user clicked ''Accept' button in `gui`.
1. Cleanup html reporter results
2. Open gui with `gemini gui` and run tests.
3. Click 'Accept' button on test result
4. Check for `data.js` in test results directory
```
metaInfo: {
url: "/user/profile",
!!!        file: "gemini\\client\\common0.js",
sessionId: "620f9e87992b35f3de509b881d08f03d"
},
```

fix: missed 'file' property in accepted result

---

lib/report-builder-factory/report-builder.js
lib/server-utils.js
test/lib/report-builder-factory/report-builder.js

fix(gui): broken images for retried tests

---

lib/static/styles.css

Accepting tall screenshots requires scrolling forth and back several times: scroll forth to compare the screenshots, and then scroll back to the "Accept" button. Sticky button minimizes scrolling.

feat: Sticky "Accept" button

---

lib/server-utils.js
test/lib/server-utils.js

It should use `fs.copyAsync` instead of `fs.copy`, because `fs.copy` expects callback (and it have not warnings about that)
Also found similair in hermione: https://github.com/gemini-testing/hermione/blob/4e6e7b99ebb39d470535d10805818f40ea6f46e1/lib/browser/commands/assert-view/capture-processors/update-refs.js#L5

fix: copyImageAsync uses non-promisified method

---

lib/merge-reports/data-tree.js
lib/merge-reports/report-builder.js
lib/plugin-adapter.js
lib/report-builder-factory/report-builder.js
lib/reporter-helpers.js
lib/server-utils.js
package-lock.json
package.json
test/gemini.js
test/hermione.js
test/lib/merge-reports/data-tree.js
test/lib/merge-reports/report-builder.js
test/lib/report-builder-factory/report-builder.js
test/lib/reporter-helpers.js
test/lib/server-utils.js
test/setup.js

fs.copy fails should be resolved in current version of fs-extra:
> [Error] ENOENT: no such file or directory, chmod '/path/to/dir.js'
links:
https://github.com/jprichardson/node-fs-extra/issues/357
https://github.com/jprichardson/node-fs-extra/issues/326

feat: update fs-extra package

---

hermione.js

One Error thrown from failHandler produce many "unhandled rejection" message.
Simple demo. 
Code:
> process.on('unhandledRejection', (reason, p) => {
>     console.error('Unhandled Rejection:\nPromise: ', p, '\nReason: ', reason);
> });
> 
> let queue = Promise.resolve();
> setTimeout(() => {
>     queue = queue.then(() => Promise.reject(new Error('111')));
> }, 0);
> 
> setTimeout(() => queue
>     .then(
>         ()=>{console.log('ok')}, 
>         (err)=>console.log('\nCatched error:  ' + err)
>     ), 100);
Output:
> Unhandled Rejection:
> Promise:  Promise {
>   <rejected> Error: 111
>     at queue.then (/Users/catwithapple/Downloads/test.js:7:45)
>     at <anonymous> }
> Reason:  Error: 111
>     at queue.then (/Users/catwithapple/Downloads/test.js:7:45)
>     at <anonymous>
> …

fix: catch unhandled reject in prepareImages

---

lib/merge-reports/data-tree.js
test/lib/merge-reports/data-tree.js

Мерж отчетов упадет, если первый сгенерирован вот такой иерархией сьютов:
```js
describe('suite', () => {
it('test1', function() {
});
});
```
а второй вот такой:
```js
describe('suite', () => {
describe('test1', function() {
it('test', () => {
})
});
});
```
Ошибка:
```
Html-reporter runtime error: TypeError: Cannot read property 'push' of undefined
```

fix(merge-reports): do not fail in case of intersecting suite and state names

---

lib/gui/tool-runner-factory/hermione/report-subscriber.js
test/lib/gui/tool-runner-factory/hermione/report-subsciber.js

// cc @DudaGod @rostik404
Если при запуске тестов через gui для одного из них стриггерить событие `TEST_PENDING`, то gui не отреагирует на это, т.к. мы не были подписаны на это событие. В результате, в gui тест подвиснет в состоянии выполнения тестов.

fix(gui): handle test skipping in runtime

---

lib/static/components/section/body/index.js
test/lib/static/components/section/body.js

В случае если тест падает с ошибками и в нем отсутствует "imagesInfo", то необходимо в опции метода drawTab добавлять ошибку из теста.
https://github.com/gemini-testing/html-reporter/pull/207/files#diff-4cc0e96c3f6c956d87595ed2822ad234R114

fix: show error info in tab which failed without any images

---

lib/report-builder-factory/report-builder.js
lib/static/components/summary/index.js
lib/static/modules/reducer.js
lib/static/modules/utils.js
lib/static/styles.css

in "ru-ru" locale
in "en-us" locale

feat: add report creation date

---

lib/static/modules/reducer.js

console error:
redux-logger.js?a9ae:1 Uncaught TypeError: Cannot read property ‘join’ of undefined
at extract (group-errors.js?5a18:34)
at extractErrors (group-errors.js?5a18:58)
at groupErrors (group-errors.js?5a18:14)
at addTestResult (reducer.js?9280:251)
at reducer (reducer.js?9280:130)
at dispatch (createStore.js?f974:165)
at eval (redux-logger.js?a9ae:1)
at eval (index.js?3446:11)
at Object.eval [as testResult] (bindActionCreators.js?83c3:3)
at EventSource.eval (main-tree.js?647a:39)

fix: forever yellow tests in gui mode after running all tests

---

lib/common-utils.js
test/lib/common-utils.js
test/lib/report-builder-factory/report-builder.js

Fix case when suite has some test with IDLE status and all branch will be marked as idle, but others tests has final status (success, fail etc)

fix(gui): idle status for suite if some of browsers has such status

---

lib/static/components/section/body/description.js
lib/static/components/section/body/meta-info.js
lib/static/components/state/screenshot.js
lib/static/components/state/state-error.js
lib/static/components/toggle-open.js
lib/static/modules/utils.js
lib/static/styles.css
test/lib/static/components/section/screenshot.js

by default screenshot is collapsed (but not NoRefImage screenshot)

feat: collapse viewport screenshot on test fail

---

lib/merge-reports/data-tree.js
lib/merge-reports/report-builder.js
test/unit/lib/merge-reports/data-tree.js

cc @DudaGod @rostik404 
У нас будут все изображения выгружаться в s3, то есть отчеты не будут фактически содержать папки images, поэтому при мерже нужно учитывать это.
Прошу обратить внимание на первый коммит, в котором (как мне кажется) удаляется неиспользуемый код.

fix(merge-reports): do not try to move images specified as urls

---

lib/static/components/section/body/meta-info.js
test/unit/lib/static/components/section/body/meta-info.js

Fix issue with rendering Meta-info when meta is object :)

fix: metaInfo serialization

---

lib/static/styles.css

Исправлен выход текста за границу блока в мета-информации и в сообщении об ошибках.
Было:
Стало:

fix: overflow meta and error text on report

---

lib/static/styles.css

fix: header controls too close to each other when they wrap

---

README.md
lib/config.js
lib/constants/defaults.js
lib/report-builder-factory/report-builder.js
lib/static/components/section/body/meta-info.js
test/unit/lib/config.js
test/unit/lib/report-builder-factory/report-builder.js
test/unit/lib/static/components/section/body/meta-info.js

В конфиге появилась новая опция `metaInfoBaseUrls`, позволяющая указать базовые Url'ы для значений Мета-информации, чтобы сделать из них соответствующие ссылки.
Напрмер, так выглядит ссылка на файл:

feat: make links from meta-info values

---

lib/gui/tool-runner-factory/base-tool-runner.js
lib/gui/tool-runner-factory/gemini/report-subscriber.js
lib/gui/tool-runner-factory/hermione/report-subscriber.js
lib/report-builder-factory/report-builder.js
lib/server-utils.js
lib/test-adapter/hermione-test-adapter.js
lib/test-adapter/test-adapter.js
test/unit/hermione.js
test/unit/lib/report-builder-factory/report-builder.js
test/unit/lib/test-adapter/hermione-test-adapter.js

Ранее массив с ретраями накапливался в `report-builder` обычным допушиванем в массив. После [рефакторинга](https://github.com/gemini-testing/html-reporter/pull/238), накапливание результата стало ассинхронным и механизм допушивания в массив уже не подходит, т.к. порядок ретраев уже не гарантирован (например, в первом ретрае мы еще сохраняем изображение, а в это время прилетел второй ретрай, для которого изображение сохранилось быстрее).
Решение - сохраняем ретраи в массив, учитывая индекс. Для этого пришлось переработать не только логику сохранения ретраев в `report-builder`, но и логику подсчета attempt в hermione-test-adapter, которая работала некорректно. Эта логика завязывалась на общее количество ретраев для прогона и поле `retriesLeft` из `hermione`, что вообще говоря неверно, т.к. …

fix: correct retries order in report

---

lib/gui/constants/server.js
lib/gui/server.js

fix for error 'net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)' on slow '/init' request.

fix: increase timeouts for GUI server

---

README.md
hermione.js
lib/config.js
lib/constants/defaults.js
lib/constants/paths.js
lib/gui/server.js
lib/gui/tool-runner-factory/hermione/report-subscriber.js
lib/report-builder-factory/report-builder.js
lib/server-utils.js
lib/static/components/section/body/error-details.js
lib/static/components/section/body/index.js
lib/static/components/state/error-details.js
lib/static/components/state/index.js
lib/static/components/state/state-error.js
lib/test-adapter/hermione-test-adapter.js
test/unit/lib/config.js
test/unit/lib/merge-reports/data-tree.js
test/unit/lib/plugin-utils.js
test/unit/lib/report-builder-factory/report-builder.js
test/unit/lib/server-utils.js
test/unit/lib/test-adapter/hermione-test-adapter.js

Основная идея ПР:
– любой плагин гермионы может докинуть в ошибку, которую он генерит, `details`;
– эти `details` должны быть формата: `{title: 'some-title', data}`;
– html-reporter сохранит `data` в папку `error-details`, в отдельный файл вида:
`short-md5(suite-path)-browser_attempt_timestamp.json`;
– а в отчет добавит `Error details`, которые раскрываясь покажут ссылку на файл с деталями ошибки; при этом `title` будет названием этой ссылки, чтобы пользователь понимал что именно содержится в этом файле, например, `counters` итп.

feat: save & show error details

---

lib/static/modules/actions.js
test/unit/lib/static/modules/actions.js

Экшен `retryTest` вызывается только после нажатия на кнопку "Retry" конкретного теста, поэтому статус `suite`-а проверять не нужно.

fix: retry only selected successful test

---

.hermione.conf.js
test/func/fixtures/.hermione.fixtures.js

Удаление опции `tunnel-identifier`, которая стала неиспользуемой после перехода на Circle CI.

test: remove tunnel-identifier from hermione config

---

lib/static/modules/reducer.js

Фильтрация тестов по браузерам в редьюсере во `VIEW_INITIAL` в режиме открытия отчета напрямую (index.html) не работает, так как это действие летит только в режиме `gui`.
С другой стороны, если перенести фильтрацию в `getInitialState`, то тогда она не будет работать в gui-режиме, так как в `gui` мы получаем данные от сервера (см. ручку `/init` в `server.js`). Поэтому фильтровать надо и там, и там.

fix: filter suites by browsers in non-gui mode

---

lib/static/gui.css

**Problem**: Buttons too small with negative zoom while trying to fit the image (heighty ones) comparison within one screen
**Proposed solution**: see PR's title
<details>
<summary>Russian</summary>
**Проблема**: При отрицательном зуме кнопки неадекватно маленького размера, по которым сложно попасть без положительного зума или пользовательских патчей стилей. Зачем зумить? Чтобы в экран поместились большие (по высоте) изображения и в рамках одного экрана увидеть дифф, а не скролить туда и обратно.
**Решение**: добавить ограничение на мин размеры
</details>

feat(gui): add min{-height, -width} to  .button_type_suite-controls class

---

README.md

Сдвинул блок с js-кодом влево, так как гитхаб глючит на нем – не может его нормально отобразить. Заодно исправил название заголовка с примером.

fix(readme): amend js-block, rename example-caption

---

README.md
lib/config/index.js
lib/constants/errors.js
lib/report-builder/report-builder-json.js
lib/static/components/state/index.js
lib/static/components/state/state-error.js
lib/static/modules/group-errors.js
lib/static/modules/reducers/reporter.js
package-lock.json
package.json
test/unit/lib/config/index.js
test/unit/lib/static/components/section/state-error.js
test/unit/lib/static/components/section/state.js
test/unit/lib/static/modules/group-errors.js
test/unit/lib/static/modules/reducers/reporter.js

Что сделано:
- при матчинге оригинальной ошибки с паттерном из `errorPatterns` вывожу первой строку `name` паттерна и под расхлопушку прячу `message` оригинальной ошибки. Также при матчинге добавляю отдельное поле `hint`, которое может быть указано в виде html строки;
- так же добавил обрезку полей ошибок по пробелу если ошибка не содержит переводов строк;

feat(error): use errorPatterns to show more understandable error info

---

lib/history-utils.js
lib/test-adapter.js
test/unit/lib/history-utils.js
test/unit/lib/static/components/section/state-error.js
test/unit/lib/static/modules/reducers/reporter.js
test/unit/lib/test-adapter.js

If an error of a failed hermione-test contains the history of all executed commands, then we show in the report all high level commands and all sub-commands of the last command.

feat: show command history on error

---

package-lock.json
package.json

On version 3.1.11 fails with `Error: Cannot find module 'webpack-cli/bin/config-yargs'`. It will be fixed later.

fix: downgrade webpack-dev-server from 3.1.11 to 2.11.5

---

lib/gui/tool-runner/index.js
lib/gui/tool-runner/utils.js
lib/report-builder/gui.js
lib/static/components/suites.js
lib/static/modules/database-utils.js
lib/static/modules/reducers/reporter.js
lib/static/modules/utils.js
lib/test-adapter.js
lib/tests-tree-builder/base.js
lib/tests-tree-builder/gui.js
lib/tests-tree-builder/static.js
test/unit/lib/common-utils.js
test/unit/lib/gui/tool-runner/index.js
test/unit/lib/report-builder/gui.js
test/unit/lib/report-builder/static.js
test/unit/lib/static/modules/reducers/reporter.js
test/unit/lib/tests-tree-builder/base.js
test/unit/lib/tests-tree-builder/gui.js
test/unit/lib/tests-tree-builder/static.js
test/unit/utils.js

- implement results tree builder for gui and static mode in order to correctly create tests tree in one place. Before that we create tests tree in three different places (gui js, sqlite static, sqlite gui) and it was hard to support;
- implement temporary backward compatibility in order to make it easier to review and debug;
- implement sort nested suites and browsers;
Normalized tests tree looks like:
```
{
suites: {byId: {}, allIds: [], allRootIds: []},
browsers: {byId: {}, allIds: []},
results: {byId: {}, allIds: []},
images: {byId: {}, allIds: []}
}
```
`suites` - store all suites (describe and it) in `byId` field without deep nesting. Each suite knows about his parent id and child suite ids (describe) or browser ids (it). Moreover `allIds` and `allRootIds` is helpful to get only …

feat: normalize redux store with temporary fallback to old format

---

lib/static/modules/reducers/index.js
lib/static/modules/reducers/tree.js

В пулл-реквесте https://github.com/gemini-testing/html-reporter/pull/359/files не учел, что нужно обновлять начальное состояние отчета с учетом выбранных браузеров.

fix(html-reporter): update init state using filter browsers

---

lib/static/modules/reducers/browsers.js

Вместо того, чтобы менять порядок подключения редьюсеров, я изменил место, в котором делаю обновление дерева на INIT. Теперь я делаю это во view, в момент, когда в состояние уже загружены браузеры фильтра.
**UPD**
Сделал проще, как советовал @DudaGod: мы не можем вытащить браузеры из state в момент инициализации gui, но можем вытащить их из action.payload

fix: correct browser filter loading in 'gui' mode

---

lib/static/modules/store.js

It makes easily to work with redux store (current state, diff, trigger `dispatch`, navigation by state's history)
https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup

chore: add support of redux-devtools in development mode

---

README.md
lib/static/.eslintrc.js
lib/static/modules/load-plugin.js
lib/static/modules/selectors/index.js
lib/static/modules/selectors/tree.js
package-lock.json
package.json
test/unit/lib/static/modules/load-plugin.js
test/unit/lib/static/modules/selectors/tree.js
test/unit/lib/static/state-utils.js

I need to get all failed tests with metadata in my plugin.
For this reason, I want to reuse redux reselect selectors.
This PR add these selectors to plugins and extend failedTests selector.

Add 'failed tests' selector in plugins

---

lib/server-utils.js
test/unit/lib/server-utils.js

В корне проекта, где используется hermione + html-reporter, всегда создается директория images с вложенными пустыми директориями под каждый тест.

fix(server-utils): fix empty directories creation in project root

---

lib/cli-commands/remove-unused-screens/utils.js
test/unit/lib/cli-commands/remove-unused-screens/utils.js

I will return `silent` flag after Hermione can to add user commands to the parser, regardless of the use `silent` flag.

fix(remove-unused-screens): temporary remove "silent" from read tests

---

hermione.js
lib/gui/tool-runner/report-subscriber.js
lib/static/components/state/index.js
lib/static/components/state/state-error.js
lib/static/modules/utils.js
lib/test-adapter.js
test/unit/lib/static/components/state/index.js
test/unit/lib/test-adapter.js

What is done:
* rename function `saveBase64Screenshot` to more correct `saveErrorScreenshot`
* fix screenshot accepting if there is error screenshot
* hide error info for "AssertViewError" errors
* hide screenshot accepting buttons for not "AssertViewError" errors

fix: correct working with screenshot on assert view fail

---

README.md
lib/constants/plugin-events.js
lib/test-adapter.js
test/unit/lib/test-adapter.js

This PR adds TEST_REPORT_READY event which gets fired after test has finished running and its screenshots have been saved.
Besides that, minor tweaks were made to make certain fields accessible from other hermione plugins.

Implement TEST_SCREENSHOTS_SAVED event

---

hermione.js
lib/gui/tool-runner/report-subscriber.js
lib/test-adapter.js
test/unit/lib/test-adapter.js

This PR fixes the following bug:
- we didn't wait for error screenshot to be saved (i.e. page screenshot) at all, because this was implemented in a different method – `saveErrorScreenshot`
Due to this, page screenshots were displayed incorrectly and `TEST_SCREENSHOTS_SAVED` event was being emitted with inconsistent screenshot data.

fix: wait for test screenshots and page screenshot on error to be saved

---

README.md
lib/constants/plugin-events.js
lib/merge-reports/index.js
lib/plugin-adapter.js
lib/plugin-api.js
lib/test-adapter.js
test/unit/lib/merge-reports/index.js
test/unit/lib/plugin-adapter.js
test/unit/lib/test-adapter.js
test/unit/utils.js

This PR adds a new event `REPORT_SAVED` which gets fired after all report files were saved. Report path is passed to the event's listeners.

feat: add REPORT_SAVED event

---

lib/gui/tool-runner/index.js

Related to https://github.com/gemini-testing/hermione/pull/720

fix: test objects should be cloned with clone method if exists

---

lib/gui/tool-runner/index.js

`test.clone` performs shallow clone of test object. We need deep clone of some properties.

fix: avoid saved test extension

---

lib/static/components/modals/screenshot-accepter/header.js
lib/static/components/modals/screenshot-accepter/index.js
lib/static/components/modals/screenshot-accepter/style.css
lib/static/components/progress-bar/index.js
lib/static/components/progress-bar/index.styl
test/unit/lib/static/components/modals/screenshot-accepter/header.js
test/unit/lib/static/components/modals/screenshot-accepter/index.js

Создал от ветки `HERMIONE-565.perf_screenshot_accepter`, так и планировалось
`screenshot-accepter progress bar` по этому коммиту: https://github.com/gemini-testing/html-reporter/pull/461/commits/b2b8a556b6431461e37a3467ef6d9dc77cd11620

feat: screenshot-accepter progress bar

---

lib/gui/tool-runner/index.js
lib/test-adapter.js
test/unit/lib/test-adapter.js

Due to https://github.com/gemini-testing/hermione/pull/742

feat: use test object id property instead of id() method

---

lib/gui/tool-runner/index.js
lib/test-adapter.js

Temporary solution to support old hermione versions. Will be removed after publish major version.

fix: support "id" field from test for old hermione versions

---

lib/gui/server.js
lib/gui/tool-runner/index.js
lib/local-images-saver.js
lib/report-builder/gui.js
lib/report-builder/static.js
lib/reporter-helpers.js
lib/server-utils.js
lib/static/modules/actions.js
lib/test-adapter.js
lib/tests-tree-builder/gui.js
package-lock.json
test/unit/hermione.js
test/unit/lib/gui/tool-runner/index.js
test/unit/lib/local-images-saver.js
test/unit/lib/report-builder/gui.js
test/unit/lib/server-utils.js
test/unit/lib/static/modules/actions.js
test/unit/lib/tests-tree-builder/gui.js

Переписал логику с отменой обновления референсов, убрал логику с удалением отмененных референсов из отчета
- Потому что пути к картинкам могут быть ссылками на ресурсы, из-за этого возникают проблемы при попытке обновить/удалить такие референсы. То, что такие картинки не удаляются, ничему не мешает
- (ну и потому что так лучше смотрится)
Локально + на скачанном отчете с путями до картинок в виде ссылок на удаленные ресурсы

fix: undo with remote images

---

lib/static/components/state/screenshot/diff-circle.js
lib/static/components/state/screenshot/resized.js
test/unit/lib/static/components/state/screenshot/diff-circle.js

Текущая имплементация достает исходный размер картинки из `target.style.width`, вместо прокидывания напрямую, из-за чего при использовании `3-up scaled to fit` `sizeCoeff`, считающийся в `diff-circle`, считается неправильно, и всегда равен единице (потому что в `3-up scaled to fit` `width`, передающийся в `style` - это уже размер уменьшенной картинки). В этом PR - фикс

fix: 3-up scaled to fit diff bubble

---

lib/static/components/modals/screenshot-accepter/header.jsx
lib/static/components/modals/screenshot-accepter/index.jsx
lib/static/components/modals/screenshot-accepter/style.css
lib/static/components/state/state-fail/index.jsx
test/unit/lib/static/components/modals/screenshot-accepter/header.jsx
test/unit/lib/static/components/modals/screenshot-accepter/index.jsx

В tinder-mode режим отображения `Diff mode` – 3 up/3 up scaled/etc. – занимает ценное вертикальное пространство.
Переносим его в выпадушку в хэдер.

fix: move diff-mode select to header for tinder-mode

---

lib/static/styles.css

Пользователи жаловались, что меню постоянно пропадает, если подвести к нему мышью под слегка неправильным углом. Чтобы этого не происходило, добавил задержку в `0.3s` перед скрытием меню.

fix: add a delay before hiding burger menu

---

lib/static/components/header/summary/summary.css
lib/static/gui.css
lib/static/styles.css
lib/static/variables.css
webpack.common.js

chore(css): sync colors for components

---

lib/test-adapter.ts
lib/types.ts
package-lock.json
package.json
test/unit/lib/test-adapter.js

- Добавил возможность не считать дифф, если он уже посчитан и передан от `hermione`
- Оставил существующую логику для обеспечения обратной совместимости
- Обновил `looks-same`, чтобы ускорить расчет диффа на новых версиях `html-reporter` со старыми версиями `hermione`

perf: use diffBuffer, provided from hermione

---

lib/static/components/state/state-error.jsx

Sometimes, sqlite database may contain `{}` in error column. In that case the whole report will crash due to trying to read property of undefined.

fix: handle absence of error message correctly

---

lib/constants/performance-marks.ts
lib/static/modules/actions.js
lib/static/modules/middlewares/metrika.js
test/unit/lib/static/modules/actions.js
test/unit/lib/static/modules/middlewares/metrika.js

Добавил метрики открытия отчета

chore: add performance metrics

---

lib/merge-reports/index.js
test/unit/lib/merge-reports/index.js

Due to a `saveStaticFilesToReportDir`'s signature change during refactoring, the merge-reports command started working incorrectly. This PR addresses this issue.

fix: fix merge-reports command

---

lib/server-utils.ts
lib/static/modules/actions.js
lib/static/modules/load-plugin.js
lib/static/modules/plugins.js
lib/static/template.html
package-lock.json
package.json
test/unit/lib/static/modules/load-plugin.js
test/unit/lib/static/modules/plugins.js

- Апнул версию форка sql.js, чтобы вместо одного большого sql-wasm.js было два файла поменьше (2МБ vs 56КБ + 620КБ)
- Исправления, направленные на устранение ожиданий загрузки файла по сети. dbUrls, sql-wasm предзагружаются в head у html, предзагрузка плагинов начинается между загрузкой баз и их слиянием, когда сеть неактивна

perf: optimize network load (preload plugins, dbUrls, split sql.js)

---

lib/merge-reports/index.js
lib/server-utils.ts
test/unit/lib/merge-reports/index.js

Если скачанный json с базами данных содержит ссылки на другие json-ы, на этапе слияния отчетов скачиваем их тоже, чтобы получить их содержимое. После чего ссылки на базы данных кладем в список ссылок на базы данных, а с ссылками на json делаем рекурсивно так же. Если json скачать не удалось, фоллбэкаем на текущую схему (кладем его в список json-ов)

perf: resolve jsonurls while merging reports

---

lib/static/variables.css

fix(css): change color for failed tests

---

lib/db-utils/server.ts
lib/merge-reports/index.js
test/unit/lib/merge-reports/index.js

Учтен случай, когда `*.json` возвращает локальную `sqlite` базу

fix: normalize urls while merging reports

---

lib/image-handler.ts

This PR addresses an issue when actual image doesn't get saved if errImg is not available. Before, it led to 500 errors when trying to accept screenshot when there's no errImg.

fix: save actual image even when errImg is not available

---

lib/static/modules/reducers/api-values.js
lib/static/modules/reducers/bottom-progress-bar.js
lib/static/modules/reducers/config.js
lib/static/modules/reducers/grouped-tests/by/meta.js
lib/static/modules/reducers/grouped-tests/by/result.js
lib/static/modules/reducers/grouped-tests/helpers.js
lib/static/modules/reducers/grouped-tests/index.js
lib/static/modules/reducers/tree/helpers.js
lib/static/modules/reducers/tree/index.js
lib/static/modules/reducers/tree/nodes/browsers.js
lib/static/modules/reducers/tree/nodes/images.js
lib/static/modules/reducers/tree/nodes/results.js
lib/static/modules/reducers/tree/nodes/suites.js
lib/static/modules/utils/index.js
lib/static/modules/utils/state.js
test/unit/lib/static/modules/reducers/grouped-tests/by/meta.js
test/unit/lib/static/modules/reducers/grouped-tests/by/result.js
test/unit/lib/static/modules/reducers/grouped-tests/index.js

Избавление от immer в статическом отчете. Вместо immer, самостоятельно храним объект с правками. Так, state остается неизменным, а правки пишутся в объект diff. Затем новый стейт формируется из старого, на который наслоен diff. К этому механизму прилагаются три хелпера: applyStateUpdate (создание нового state из старого и diff), ensureDiffProperty (создание вложенного объекта при необходимости, используется при передаче diff в другую функцию), getUpdatedProperty (достает проп из state, учитывая, что он может быть перезаписан в diff).
В среднем, на больших отчетах задержка от `immer` при действиях - от 400 (если у пользователя мощное устройство и задействован только один тяжелый редьюсер (`tree / grouped tests`)) до 1600 (если у пользователя более слабое устройство и задействовано сразу …

perf: remove immer from static report

---

lib/common-utils.ts
test/unit/lib/common-utils.ts

This PR addresses an issue when the "view in browser" button doesn't respect the baseHost setting.

fix: correctly handle baseUrl when generating test result

---

lib/static/components/modals/screenshot-accepter/body.jsx
lib/static/components/modals/screenshot-accepter/style.css
lib/static/components/progress-bar/index.styl
lib/static/components/state/state-fail/index.jsx
lib/static/styles.css
test/unit/lib/static/components/modals/screenshot-accepter/body.jsx

feat(screenshot-accepter): add more space for screenshot view

---

lib/test-adapter/playwright.ts
test/unit/lib/test-adapter/playwright.ts

- Добавил возможность отображения результата успешного сравнения в отчете (если передается)
- Прокидывается `refImg`. В отчете отображается именно он (https://github.com/gemini-testing/html-reporter/blob/master/lib/static/components/state/index.jsx#L161. В коде `expectedImg`, но он получается из `refImg`)

fix(playwright): display provided image on screenshot match

---

lib/errors/index.ts
lib/static/components/state/index.jsx
lib/test-adapter/hermione.ts
lib/types.ts
package-lock.json
package.json
test/unit/lib/test-adapter/hermione.ts

- add different pixels value, which is displayed when using hermione >= 8.2.0
hermione types fix: https://github.com/gemini-testing/hermione/pull/852

feat: display differentPixels, if available

---

lib/images-info-saver.ts
test/unit/lib/images-info-saver.ts

fix: ensure right image states order html-reporter

---

lib/static/styles.css

fix: align the menu icon with the rest of the items

---

package-lock.json
package.json
playwright.ts

The static report has stopped working with the new version of the playwright (checked with version 1.44.1). the problem is that playwright has started transferring some of its private fields (`_mode`, `_isTestServer` and `_commandHash` to all connected reports) and this leads to an error:
```
UnknownKeysError: Unknown options: root._mode, root._isTestServer, root._commandHash
```
So I ignore them and everything works fine.

fix(pwt): ignore private report options from pwt

---

lib/static/components/controls/test-name-filter-input.jsx
lib/static/components/section/title/browser.jsx

If test name contains brackets or other special characters, copied link becomes invalid because our search starts treating those brackets as part of a regexp.

fix: escape regexp chars when copying a test link

---

lib/static/components/controls/run-button/index.jsx
test/unit/lib/static/components/controls/run-button.jsx

Save the state of the run tests button. Default state: run failed.

fix: save RunMode to localStorage

---

lib/gui/tool-runner/index.ts
lib/types.ts
test/unit/lib/gui/tool-runner/index.js

Add `relativePath` to `refImg` when creating test result after accepting new image reference, just like Testplane@8.13.0 does it.
Branch created from #551, as it changes the way test result is created

feat: add relativePath to refImg

---

CHANGELOG.md
lib/static/components/section/body/meta-info/content.jsx
lib/static/styles.css
package-lock.json
package.json

Added "copy to clipboard" button to all fields in meta. The button is hidden by default an is revealed on hover.

feat: add copy to clipboard button to all fields in meta

---

lib/gui/tool-runner/index.ts
lib/report-builder/static.ts
test/unit/lib/gui/tool-runner/index.js

The idea is to calc new result state based on the latest result, not the current one

fix: result state after screenshot-accepter image accept

---

lib/adapters/config/index.ts
lib/adapters/config/testplane.ts
lib/adapters/test-collection/index.ts
lib/adapters/test-collection/testplane.ts
lib/adapters/test-result/playwright.ts
lib/adapters/test-result/testplane.ts
lib/adapters/test/index.ts
lib/adapters/test/testplane.ts
lib/adapters/tool/index.ts
lib/adapters/tool/testplane/index.ts
lib/adapters/tool/testplane/runner/all-test-runner.ts
lib/adapters/tool/testplane/runner/specific-test-runner.ts
lib/cli/commands/remove-unused-screens/utils.js
lib/gui/app.ts
lib/gui/tool-runner/index.ts
test/unit/lib/adapters/config/testplane.ts
test/unit/lib/adapters/test-collection/testplane.ts
test/unit/lib/adapters/test/testplane.ts
test/unit/lib/adapters/tool/testplane/index.ts
test/unit/lib/cli/commands/remove-unused-screens/utils.js
test/unit/lib/gui/app.js
test/unit/lib/gui/tool-runner/index.js
test/unit/utils.js
testplane.ts

Implement adapters: test, testCollection and config. In order to support gui command for playwright.
Previous PR with implementation tool adapter - https://github.com/gemini-testing/html-reporter/pull/551.
After that PR, I will be able to implement the launch of playwright tests using gui command.

chore: implement adapters: test, testCollection, config

---

lib/bundle/constants.ts
lib/bundle/index.ts
lib/bundle/transformer.ts
package-lock.json
package.json

Adds ability to require files with extensions: '.ts', '.mts', '.mjs'.
It is preliminary step before implementing the launch of playwright tests using gui command.
This logic is used from testplane, commit - https://github.com/gemini-testing/testplane/pull/906/commits/d050dedc4a5a6da089737aa77089049bb88476fe

chore: ability to read pwt config with extension: .ts, .mts and .mjs

---

lib/gui/tool-runner/index.ts
lib/report-builder/gui.ts
lib/report-builder/static.ts
playwright.ts
test/unit/lib/report-builder/gui.js
test/unit/lib/report-builder/static.js
testplane.ts
tsconfig.json

- exclude "bundle" folder in tsconfig
- refactoring in report builders (just send one argument with all options)
There is nothing to review here, so I merge it without approve.

refactor: use one argument with all options inside report builders

---

lib/adapters/test-result/playwright.ts
lib/adapters/test-result/sqlite.ts
lib/cli/index.ts
lib/common-utils.ts
lib/constants/tests.ts
lib/db-utils/server.ts
lib/gui/tool-runner/index.ts
lib/plugin-api.ts
lib/report-builder/gui.ts
lib/static/modules/actions.js
lib/tests-tree-builder/base.ts
lib/tests-tree-builder/static.ts
test/unit/lib/adapters/test-result/playwright.ts

- handle "uncaughtException" and "unhandledRejection" when using cli commands from html-reporter binary file
- use default title delimiter - " " (one space) for all supported tools. If tool used another title delimiter then it must modify it to default inside adapters. In the process of implementing support pwt in gui command I realized that it's easier to support (no need to send tool name in a bunch of files and call a special helper to get correct delimiter).

chore: use default title delimiter for all supported tools

---

lib/adapters/config/index.ts
lib/adapters/tool/index.ts
lib/adapters/tool/testplane/index.ts
lib/gui/app.ts
lib/gui/index.ts
lib/gui/server.ts
lib/gui/tool-runner/index.ts
test/unit/lib/adapters/tool/testplane/index.ts
test/unit/lib/gui/app.js
test/unit/lib/gui/tool-runner/index.js
test/unit/utils.js

- move logic with run tests without retries from `lib/gui/app` to `lib/adapters/tool/testplane`. Because other tools should implement it by themself. 
- add method `runWithoutRetries` which must be implemented in each tool adapter.

chore: move logic with change retries to testplane adapter

---

lib/report-builder/gui.ts
lib/server-utils.ts
lib/static/components/controls/report-info.jsx
lib/static/modules/reducers/index.js
lib/static/modules/reducers/timestamp.js

- add "timestamp" field to redux storage in order to use from plugins
- filed "date" will be removed in next major version

feat: add "timestamp" field to redux storage

---

lib/adapters/test-result/testplane.ts
test/unit/lib/adapters/test-result/testplane.ts

Now (test has failed status, and no error message is shown, though there was an error):
After this PR (test has error status and error message is shown):

fix: return correct test result status

---

.github/workflows/node.js.yml

Switching to node 22.x as the bug with node 22.5 was fixed in 22.5.1

chore: use upstream node@22

---

lib/static/components/controls/browser-list/index.jsx
lib/static/components/suites.jsx
test/unit/lib/static/components/suites.jsx

fix: display a human-readable error message when report is completely empty

---

lib/static/modules/reducers/tree/nodes/suites.js
test/unit/lib/static/modules/reducers/tree/index.js

`failSuites` function is used to fail parent suites after "undo"
In this PR, i added a check in order to not add parent "null" to our loop

fix: undo accept image

---

lib/static/components/controls/selects/control.jsx
lib/static/components/controls/selects/group-tests.jsx

Fixes an issue when select dropdowns are positioned wrong when header is hidden
Test report: https://nda.ya.ru/t/R93-0jax77g2LS

fix: disable portal for header select elements

---

lib/static/new-ui/features/suites/components/BrowsersSelect/BrowserIcon.tsx
lib/static/new-ui/features/suites/components/BrowsersSelect/index.module.css
lib/static/new-ui/features/suites/components/BrowsersSelect/index.tsx
lib/static/new-ui/features/suites/components/SuitesPage/index.tsx
lib/static/new-ui/types/store.ts
lib/tests-tree-builder/static.ts
lib/types.ts

Test report: https://nda.ya.ru/t/Swx3j5CU77fYFH
⚠️ This PR is based on #592, only last commit needs review (`feat: implement filtering by browser`)

feat: implement filtering by browser in new ui

---

lib/static/new-ui/components/Card/KeepDraggingToHideCard.module.css
lib/static/new-ui/components/Card/KeepDraggingToHideCard.tsx
lib/static/new-ui/components/Card/index.module.css
lib/static/new-ui/components/Card/index.tsx
lib/static/new-ui/components/SplitViewLayout.module.css
lib/static/new-ui/components/SplitViewLayout.tsx
lib/static/new-ui/features/suites/components/SuitesPage/index.module.css
lib/static/new-ui/features/suites/components/SuitesPage/index.tsx
lib/static/styles.css

Only last commit needs review.
Demo report: https://nda.ya.ru/t/MauDnu4i78HAjg

chore(new-ui): implement drag to hide hint card

---

lib/adapters/test-result/reporter.ts
lib/adapters/test-result/transformers/tree.ts

It turned out that after refactoring, `extractErrorDetails` is called several times - https://github.com/gemini-testing/html-reporter/blob/v10.7.0/lib/adapters/test-result/utils/index.ts#L50-L64 which builds the path to the file and calls `Date.now()` inside it. As a result, each call generates a unique path. And one is used for link inside html-reporter and another for save file in folder.
Now we will use the already existing value.

fix: correctly build link to error details

---

lib/constants/features.ts
lib/static/modules/reducers/gui.js
lib/static/modules/utils/index.js
lib/static/new-ui.css
lib/static/new-ui/components/AssertViewResult/index.module.css
lib/static/new-ui/components/AssertViewResult/index.tsx
lib/static/new-ui/components/AssertViewStatus/index.module.css
lib/static/new-ui/components/AssertViewStatus/index.tsx
lib/static/new-ui/components/AttemptPicker/index.module.css
lib/static/new-ui/components/CompactAttemptPicker/index.module.css
lib/static/new-ui/components/CompactAttemptPicker/index.tsx
lib/static/new-ui/components/DiffViewer/index.module.css
lib/static/new-ui/components/DiffViewer/index.tsx
lib/static/new-ui/components/ImageLabel/index.module.css
lib/static/new-ui/components/ImageLabel/index.tsx
lib/static/new-ui/features/suites/components/ScreenshotsTreeViewItem/index.module.css
lib/static/new-ui/features/suites/components/ScreenshotsTreeViewItem/index.tsx
lib/static/new-ui/features/suites/components/TestSteps/index.tsx
lib/static/new-ui/features/visual-checks/components/VisualChecksPage/index.module.css
lib/static/new-ui/features/visual-checks/components/VisualChecksPage/index.tsx
lib/static/new-ui/types/store.ts
lib/static/new-ui/utils/index.tsx

⚠️ Only **last three commits** need review.
What's done:
- Ability to accept/undo screenshots
- Tweaks to tinder mode, including compact attempt picker and status display
- Other minor fixes
Test report: https://nda.ya.ru/t/TDDrfcZG78eWpd

feat(new-ui): add ability to accept and undo screenshots

---

lib/static/new-ui/features/suites/components/SuitesTreeView/selectors.ts

⚠️ Only last commit needs review
Fixed a crash when full title differs from id

fix(new-ui): use actual ids in selectors instead of fulltitle

---

lib/constants/local-storage.ts
lib/static/components/controls/browser-list/index.jsx
lib/static/components/controls/controls.less
lib/static/components/controls/report-info.jsx
lib/static/hooks/useLocalStorage.js
lib/static/new-ui.css
lib/static/new-ui/app/App.tsx
lib/static/new-ui/components/AttemptPicker/index.module.css
lib/static/new-ui/components/LoadingBar/index.module.css
lib/static/new-ui/components/MainLayout/Footer.tsx
lib/static/new-ui/components/MainLayout/index.module.css
lib/static/new-ui/components/MainLayout/index.tsx
lib/static/new-ui/components/SettingsPanel/index.module.css
lib/static/new-ui/components/SettingsPanel/index.tsx
lib/static/new-ui/components/SplitViewLayout.tsx
lib/static/new-ui/components/SuiteTitle/index.module.css
lib/static/new-ui/components/SuiteTitle/index.tsx
lib/static/new-ui/components/UiModeHintNotification/index.module.css
lib/static/new-ui/components/UiModeHintNotification/index.tsx
lib/static/new-ui/features/suites/components/ScreenshotsTreeViewItem/index.module.css
lib/static/new-ui/features/visual-checks/components/VisualChecksPage/index.module.css
lib/static/template.html

- Go to new UI button in old UI
- Settings panel with go back to old UI
- The choice of UI mode is remembered
Demo report: https://nda.ya.ru/t/dW1Fx8qe78xojb
Demo GIF: https://nda.ya.ru/t/Il_hVvfw78xoku

feat: implement a button to switch between new and old UI

---

lib/adapters/test-result/testplane.ts
lib/common-utils.ts
lib/errors/index.ts
lib/static/components/state/state-error.jsx
lib/static/modules/utils/index.js
lib/static/new-ui/components/AssertViewStatus/index.tsx

fix: handle invalid ref image errors

---

lib/static/new-ui/components/SuiteTitle/index.module.css
lib/static/new-ui/components/SuiteTitle/index.tsx

When a test is not nested in any describe, heading has padding that's too large. This PR fixes that.
Test report: https://nda.ya.ru/t/ZH3rtNfr79sg3u

fix: fix large padding on top of test card when there is no describe

---

lib/static/new-ui/features/suites/components/TestSteps/selectors.ts
lib/static/new-ui/store/selectors.ts

Previously in pwt visual assertions were added as "assertView" commands at the end of the test. This PR makes it so that they are added to corresponding toMatchScreenshot commands.
Demo report: https://nda.ya.ru/t/jzvnUjB779sizC

fix: add playwright visual checks results to correct steps in new ui

---

lib/adapters/test-result/testplane.ts
lib/common-utils.ts
lib/static/components/section/section-browser.jsx
lib/static/new-ui/components/AttemptPickerItem/index.module.css
lib/static/new-ui/components/MetaInfo/index.tsx
lib/static/new-ui/features/suites/components/SuitesPage/types.ts
lib/static/new-ui/features/suites/components/SuitesTreeView/index.module.css
lib/static/new-ui/features/suites/components/SuitesTreeView/selectors.ts
lib/static/new-ui/features/suites/components/TestSteps/index.tsx
lib/static/new-ui/features/suites/components/TreeViewItemSubtitle/index.module.css
lib/static/new-ui/features/suites/components/TreeViewItemSubtitle/index.tsx
lib/static/new-ui/types/store.ts
lib/static/new-ui/utils/index.tsx
test/unit/lib/static/components/section/section-browser.jsx

- Skip reason is now displayed as part of preview in tree view in new ui
- Skip reason is displayed in meta when possible
Demo report: https://nda.ya.ru/t/Ba_4zPC979ttwt

fix: display skip reason in new ui

---

lib/static/components/modals/screenshot-accepter/index.jsx
lib/static/modules/utils/imageEntity.ts
lib/static/modules/utils/index.js
lib/static/new-ui/components/SuiteTitle/index.tsx
lib/static/new-ui/features/visual-checks/components/VisualChecksPage/index.tsx
lib/static/new-ui/features/visual-checks/selectors.ts
test/unit/lib/static/components/modals/screenshot-accepter/index.jsx
test/unit/lib/static/new-ui/features/visual-checks/components/VisualChecksPage.jsx

Added image prefetching in new ui
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.

feat(new-ui): add image prefetch in new ui

---

.eslintignore
lib/adapters/event-handling/testplane/snapshots.ts
lib/adapters/test-result/index.ts
lib/adapters/test-result/playwright.ts
lib/adapters/test-result/reporter.ts
lib/adapters/test-result/sqlite.ts
lib/adapters/test-result/testplane.ts
lib/cli/commands/merge-reports.js
lib/constants/database.ts
lib/db-utils/server.ts
lib/merge-reports/index.js
lib/server-utils.ts
package-lock.json
package.json
test/unit/lib/merge-reports/index.js
test/unit/lib/server-utils.js

Previously, merge reports only worked with urls on `databaseUrls.json` and `sqlite.db`. If user send path to these files on file system merge was complete successfully but in merged report the tests were not displayed.
So in this PR I fix this behaviour and now merge reports correctly work with files on fs.
What can be improved: ability to path just a folder.

fix(merge-reports): ability to merge reports locally

---

.npmignore

the directory `test` was lost form `adapters` folder when I published new version to npm

chore: use /test forlder in npmignore file

---

lib/adapters/event-handling/testplane/snapshots.ts
lib/adapters/tool/testplane/index.ts

fix: fix compatibility with older testplane versions and stop writing invalid warnings

---

lib/static/modules/reducers/suites-page.ts
lib/static/new-ui/app/App.tsx
lib/static/new-ui/components/CompactAttemptPicker/index.tsx
lib/static/new-ui/components/TreeActionsToolbar/index.tsx
lib/static/new-ui/components/TreeView/index.tsx
lib/static/new-ui/features/suites/components/ScreenshotsTreeViewItem/index.module.css
lib/static/new-ui/features/suites/components/ScreenshotsTreeViewItem/index.tsx
lib/static/new-ui/features/suites/components/SuitesPage/index.tsx
lib/static/new-ui/features/suites/components/SuitesPage/selectors.ts
lib/static/new-ui/features/suites/components/TestSteps/index.tsx
lib/static/new-ui/features/suites/selectors.ts
lib/static/new-ui/features/visual-checks/components/VisualChecksPage/VisualChecksStickyHeader.tsx
lib/static/new-ui/features/visual-checks/components/VisualChecksPage/index.tsx
lib/static/new-ui/features/visual-checks/selectors.ts
test/func/tests/common/new-ui/visual-checks-page/main-functionality.testplane.js
test/unit/lib/static/new-ui/features/visual-checks/components/VisualChecksStickyHeader.jsx

Немного поменял урлы на страницах suites и visual checks теперь так
http://localhost:8000/new-ui#/visual-checks/:imageId/:attempt
http://localhost:8000/new-ui#/suites/:browserId/:stateName/:attempt
Теперь номер попытки и имя стейта сохраняется в урле
Вот примеры
http://localhost:8000/new-ui#/visual-checks/test%20example%20%230%20chrome%20main-element/2
http://localhost:8000/new-ui#/suites/test%20example%20%230%20chrome/main-element/2

feat(move-button): button for fast move between visual checks and suites

---

lib/cli/commands/remove-unused-screens/index.js
lib/cli/commands/remove-unused-screens/utils.js
lib/server-utils.ts
package-lock.json
package.json
test/unit/lib/cli/commands/remove-unused-screens/index.js
test/unit/lib/cli/commands/remove-unused-screens/utils.js
test/unit/testplane.js
webpack.common.js

- Splitted webpack chunks, extracting common code, which reduced build time (by 4.5 seconds) and bundles size:
<table>
<tr>
<td align="center"><b>Before</b></td>
<td align="center"><b>After</b></td>
</tr>
<tr>
<td>
</td>
<td>
<table>
<tr>
<td>
</td>
</tr>
</table>
</td>
</tr>
</table>
- Removed `@babel/runtime` out from prod deps
- Replaced old "inquirer" with new light "@inquirer/confirm"

chore: optimize package size

---

lib/static/new-ui/components/Card/UiCard.module.css
lib/static/new-ui/components/ErrorInfo/index.module.css
lib/static/new-ui/components/ImageWithMagnifier/index.module.css
lib/static/new-ui/components/ImageWithMagnifier/index.tsx
lib/static/new-ui/components/SideBar/index.module.css
lib/static/new-ui/components/SideBar/index.tsx
lib/static/new-ui/components/TabsSelect/index.tsx
lib/static/new-ui/components/TreeActionsToolbar/index.module.css
lib/static/new-ui/components/TreeActionsToolbar/index.tsx
lib/static/new-ui/components/TreeView/index.module.css
lib/static/new-ui/components/TreeView/index.tsx
lib/static/new-ui/components/TreeViewItem/index.module.css
lib/static/new-ui/components/TreeViewItem/index.tsx
lib/static/new-ui/components/TreeViewItemIcon/index.module.css
lib/static/new-ui/components/TreeViewItemSubtitle/index.module.css
lib/static/new-ui/components/TreeViewItemSubtitle/index.tsx
lib/static/new-ui/features/suites/components/SuitesPage/index.module.css
lib/static/new-ui/features/visual-checks/components/VisualChecksPage/index.module.css
test/func/tests/common/new-ui/visual-checks-page/main-functionality.testplane.js

- Tree view items now have more modern and sleek look, with slightly more rounded edges and similar items "sticking" to each other:
- Scrollbar no longer interferes with checkboxes on MacOS:
- Tree view items no longer jump vertically when new images are being loaded. Scroll experience is now smooth and consistent.

fix: fix jitter during images load in tree view, enhance tree items visuals and fix scrollbar interfering with checkboxes
